class AppConstants {
  static const String appName = "FARYAL.EXE";
  
  static const List<String> randomFacts = [
    "I probably know someone you know.",
    "I have 1000 things to say.",
    "I'm overthinking.",
    "I'm hungry.",
    "I made another new friend.",
    "I wasn't ignoring you, I was charging.",
    "I'm actually a dinosaur in disguise.",
    "My social battery is either 100% or 0%, no in-between.",
    "I have a screenshot for every situation.",
    "I'm not short, I'm 'Pocket Edition™'.",
    "I can talk about nothing for 3 hours straight.",
    "I'm 99% kindness and 1% concentrated dinosaur energy.",
    "I probably already have a plan for our next 5 meetings.",
    "I'm not weird, I'm just on a different frequency.",
    "I find friends in the most random places.",
    "I'm a professional at starting conversations with strangers.",
    "I have a PhD in Overthinking.",
    "My brain has 50 tabs open, and I don't know where the music is coming from.",
    "I'm a human version of unlimited data.",
    "I make people comfortable for a living.",
    "I'm actually very shy (only around 10% of the time).",
    "I'm a certified 'Safe Person'.",
    "I turn ideas into art when I'm bored.",
    "I'm a Mehendi artist by day, dinosaur by night.",
    "I've probably seen that meme already.",
    "I'm a human sunshine, occasionally with a little rain.",
    "I'm sensitive to everything, including the temperature of the room.",
    "I can read your vibe from a single text.",
    "I'm a collector of random memories.",
    "I have 100 unread screenshots in my gallery.",
    "I'm the person who asks 'How are you?' and actually waits for the answer.",
    "I'm a conversation starter expert.",
    "I'm professionally unique.",
    "I'm made of Flutter, Coffee, and HTML memories.",
    "I have a legendary trust level.",
    "My dinosaur energy is currently 999%.",
    "I'm a creative soul trapped in a human body.",
    "I've made a new friend in under 5 minutes before.",
    "I'm a professional yapper.",
    "I'm 120% talkative.",
    "My shyness is a random encounter.",
    "I'm 110% weirdness.",
    "I'm a certified listener.",
    "I'm a random meme generator.",
    "I'm human sunshine.",
    "I'm a professional overthinker.",
    "I'm a creative soul.",
    "I'm a mehendi artist.",
    "I'm a conversation starter.",
    "I'm a safe person.",
  ];

  static const List<String> popupMessages = [
    "Achievement Unlocked: You survived another conversation.",
    "Breaking News: Faryal found another friend.",
    "Alert: Overthinking started.",
    "Reminder: Drink water.",
    "Loading... Finding brain cell... Still searching...",
    "System Update: Kindness levels exceeding limits.",
    "Warning: Social battery at 5%. Please plug into a friend.",
    "Dinosaur Alert: Rawr means I love you in dinosaur.",
  ];
}
